server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/phone_review?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
  jackson:
    default-property-inclusion: non_null

# mybatis-plus配置
mybatis-plus:
  configuration:
    # MyBatis 配置
    map-underscore-to-camel-case: true
  mapper-locations: classpath:/mapper/**.xml
  global-config:
    # 全局配置
    db-config:
      # 数据库配置
      id-type: auto

# 静态资源配置
application:
  file:
    path: D:/GraduationDesign/phone_review/images/
  url:
    prefix: http://localhost:8080/images/

logging:
  level:
    com:
      svwh:
        phonereview:
          mapper: debug

# 配置邮件发送账号
mail-service:
  mail-infos:
    - host-name: smtp.qq.com
      username: cmanager@qq.com
      password: ccfsywtccmjxeahj
      from-sender: cmanager@qq.com
      sender-rank: 3
    - host-name: smtp.qq.com
      username: 480252715@qq.com
      password: amuixyxrpdbmbhjb
      from-sender: 480252715@qq.com
      sender-rank: 4
    - host-name: smtp.163.com
      username: cxkchenxin@163.com
      password: WYHFMEUWWRSBEXNQ
      from-sender: cxkchenxin@163.com
      sender-rank: 8
